config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server, :at => "/resque"

  resources :tools, :posts, :sessions, :users, :events

  resource :calendar, only: [:show], controller: :calendar

  get   "/home/index",            to: "home#index",    as: :home_index
  root                                "home#index",    as: :root

  get   '/auth/twitter/callback', to: 'users#create',  as: :twitter_callback
  post  '/auth/twitter/callback', to: 'users#create'

  get   '/users/:id/confirm',      to: 'users#confirm', as: :confirm_user

  get   '/users/:id/deny_admin',    to: 'users#deny_request', as: :deny_request

  get   '/users/:id/9847hfh9f824oifnsdlkvhosiehlrisklevishfleh', to: 'users#admin_request'
  get   '/users/:id/4ruoirwnv24vpoifho4ehvjrhg4owihfaoihfaajksdhviuwgifbw4f', to: 'users#become_admin', as: :adminify

end

app/models/tool.rb
class Tool < ActiveRecord::Base
  belongs_to :user
  validates :name, :img, presence: true

  def checkout(user_id)
    self.user_id = user_id
    self.availability = false
    self
  end

  def put_back
    self.user_id = nil
    self.availability = true
    self.save
  end

  def self.sort_tools
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tool = Tool.new
    @tools = []
    used = []
    unavailable = []
    avail = []
    touhlz = Tool.all
    if @current_user
      touhlz.each do |f|
        if (f.availability == false) && (f.user_id == @current_user.id)
          @tools << f
        elsif f.availability == true
          used << f
        elsif f.availability == false && f.user_id != @current_user.id
          avail << f
        else
          unavailable << f
        end
      end
    else
      @tools = touhlz
    end
    (@tools << used).flatten!
    (@tools << avail).flatten!
    (@tools << unavailable).flatten!
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      redirect_to tools_path
    else
      render 'index'
    end
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.availability
      @tool.checkout(@current_user.id)
    else
      @tool.put_back
    end
    @tool.save
    # json or html; can put hash here if you need it.
    # render json: []
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:id, :name, :img, :availabilty, :user_id)
  end

end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/index.html.erb
<!-- Button trigger modal -->
<br>
<% if @current_user && @current_user.admin %>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Add New Tool
  </button>
<% end %>

<!-- Modal -->
<% if @current_user %>
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop = "false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        </div>
        <div class="modal-body">
          <div class="modal-body">
            <%= bootstrap_form_for @tool, url: { action: "create" } do |f| %>
              <%= f.text_field :name, label: "Tool Name" %>
              <!-- current_user.user.user_id -->
              <%= f.hidden_field :user_id, :value => @current_user.id %>
              <%= f.hidden_field :availability %>
              <%= f.text_field :img, label: "Image URL"%>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= f.submit "Save", class: "btn btn-default"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<!-- <div class="media">
  <a class="media-left media-middle" href="#">
    <img data-src="https://placekitten.com/g/200/300">
  </a>
  <div class="media-body">
    <h4 class="media-heading">Middle aligned media</h4>
    ...
  </div>
</div> -->
<br>
<!-- <div class="media"> -->
  <% @tools.each do |tool| %>
    <hr>
    <br>
    <div class =" media media-image">
      <img src="<%= tool.img %>" height="125px">
    </div>
    <br>
    <br>
    <div class="media media-body">
      <h4 class="media-heading">
        <%= tool.name %>
      </h4>
      <% if @current_user %>
        <!-- <div class="tools media media-button"> -->
          <%= bootstrap_form_for tool, url: tool_path(tool.id) do |f| %>
            <%= f.hidden_field :user_id, :value => @current_user.id %>
            <% if (tool.availability == false) && (tool.user_id == @current_user.id) %>
              <%= f.submit "Return Tool", class: "choose btn btn-danger" %>
            <% elsif tool.availability == true %>
              <%= f.submit "Check Out Tool", class: "choose btn btn-success" %>
            <% elsif tool.availability == false && tool.user_id != @current_user.id%>
              <%= f.submit "Checked Out", class: "btn btn-default", disabled: "disabled"%>
            <% end %>
          <% end %>
      <% end %>
    </div>
  <!-- </div> -->
    <br>
  <% end %>
<!-- </div> -->
<br>
<br>
<!-- <% if @current_user %> -->
<!-- <div class="media">
  <% @tools.each do |tool| %>
    <div class ="media-image">
      <img src="<%= tool.img %>" height="125px">
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= tool.name %></h4>
    </div>
    <div class="media-button">
      <%= bootstrap_form_for tool, url: tool_path(tool.id) do |f| %>
        <%= f.hidden_field :user_id, :value => @current_user.id %>

        <% if (tool.availability == false) && (tool.user_id == @current_user.id) %>
          <%= f.submit "Return Tool", class: "choose btn btn-danger" %>
        <% elsif tool.availability == true %>
          <%= f.submit "Check Out Tool", class: "choose btn btn-success" %>
        <% elsif tool.availability == false && tool.user_id != @current_user.id%>
          <%= f.submit "Checked Out", class: "btn btn-default", disabled: "disabled"%>
        <% end %>
      <% end %>
    </div>
    <br>
  <% end %>
</div> -->
<!-- <% end %> -->