config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server, :at => "/resque"

  resources :tools, :posts, :sessions, :users, :events

  resource :calendar, only: [:show], controller: :calendar

  get   "/home/index",            to: "home#index",    as: :home_index
  root                                "home#index",    as: :root

  get   '/auth/twitter/callback', to: 'users#create',  as: :twitter_callback
  post  '/auth/twitter/callback', to: 'users#create'

  get   '/users/:id/confirm',      to: 'users#confirm', as: :confirm_user

  get   '/users/:id/deny_admin',    to: 'users#deny_request', as: :deny_request

  get   '/users/:id/9847hfh9f824oifnsdlkvhosiehlrisklevishfleh', to: 'users#admin_request'
  get   '/users/:id/4ruoirwnv24vpoifho4ehvjrhg4owihfaoihfaajksdhviuwgifbw4f', to: 'users#become_admin', as: :adminify

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tools
  has_many :posts

  validates :name, :uid, presence: true, uniqueness: true
  #:email,
  # validates :admin, class: Boolean

  # validates :email, format: { with: /@/ }

  def adminify
    self.admin = true
  end

  def turn_down
    self.admin = false
  end

  def confirm
    self.confirmed = true
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    auth_hash = request.env['omniauth.auth']
    @user = User.find_by_uid(auth_hash.uid)
    if @user
      session[:user_id] = @user.id
      @current_user = current_user
      redirect_to root_path
    else
      @user = User.new(uid: auth_hash.uid, name: auth_hash.info.name)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user.id)
      else
        redirect_to @user
      end
    end
  end

  def show
    @user = @current_user
    @user.admin == "true" ? @admin = true : @admin = false
    @users = User.where(admin: nil, confirmed: true)
  end

  def update
    @user = @current_user
    email1 = @user.email
    @user.update(params.require(:user).permit(:name, :email))
    if params[:user][:admin] == "1"
      @user.admin = nil
      @user.save
    end
    email2 = @user.email
    unless email1 == email2
      @user.confirmed = false
      @user.save
      Resque.enqueue(EmailSubscribeJob, @user.id)
      flash[:notice] = "Expect an email confirming your subscription shortly!"
    end
    flash[:notice] = "Your account has been updated!"
    redirect_to @user
  end

  def destroy
    @user = @current_user
    @user.tools.each do |tool|
      tool.put_back
    end
    if @user.destroy
      session[:user_id] = nil
      redirect_to root_path
    else
      render "show"
    end
  end

  def confirm
    @user = @current_user
    @user.confirm
    @user.save
    redirect_to @user
  end

  def become_admin
    @user = User.find(params[:id])
    if @user.confirmed
      @user.adminify
    else
      render "admin_request"
    end
    @user.save
    redirect_to @current_user
  end

  def deny_request
    @user = User.find(params[:id])
    @user.turn_down
    @user.save
    redirect_to user_path(@current_user.id)
  end

  def admin_request
    @user = @current_user
  end

  private


end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_request.html.erb
<p>
  So, <%= @user.name %>, you've learned the secret url,
  and would like to become an admin.
</p>

<% if @user.confirmed %>
  <p>
   Go ahead, click this
   <%= link_to "button", adminify_path(@user), class: "btn btn-default" %>,
   and adminify yourself!
 </p>
<% else %>
  <p>
    Before you can become an admin,
    you must submit and confirm your email address.
  </p>
<% end %>

app/views/users/show.html.erb
<h2>Hello, <%= @user.name %></h2>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <div class="center"> <%= flash[:notice] %> </div>
  </div>
<% end %>

<%= bootstrap_form_for(@user) do |f| %>
  <div id="edit-name">
    <%= f.text_field :name %>
  </div>
  <div id="edit-email">
    <% if @user.email %>
      <% unless @user.confirmed %>
      <div class="alert alert-warning" role="alert">
        Email Unconfirmed
      </div>
      <% end %>
      <%= f.email_field :email %>
    <% else %>
      <%= f.email_field :email, placeholder: "Add your email to get updates about garden events and news!" %>
    <% end %>
    <% if @user.admin %>

    <% elsif @user.admin == nil %>
      <div class="alert alert-warning" role="alert">
        Your admin request has been received and will be evaluated by a current admin.
      </div>
    <% elsif @user.admin == false && @user.confirmed %>
      <%= f.check_box :admin, label: "Request admin status" %>
    <% else %>

      <div class="alert alert-warning" role="alert">
        Submit and confirm an email address in order to request admin status.
      </div>
    <% end %>
  </div>
    <%= f.submit class: "btn btn-default", value: "Update Account"%>
<% end %>

<br>
<%= link_to "Delete Your Account", @user, method: :delete, class: "btn btn-default" %>

<% if @user.admin %>
  <hr>
  <div class = "buttonz">
    <button type="button" class="btn btn-default space">
      <%= link_to "Schedule an Event", calendar_path %>
    </button>
    <button type="button" class="btn btn-default space">
      <%= link_to "Add a Tool", tools_path %>
    </button>
    <button type="button" class="btn btn-default space">
      <%= link_to "Write a Post", new_post_path %>
    </button>
  </div>
  <hr>
  <% if @users.length > 0 %>
    <h3>Admin candidates:</h3>
    <% @users.each do |user| %>
      <%= user.name %>
      <%= link_to "Make admin", adminify_path(user.id), class: "btn btn-default" %>
      <%= link_to "Deny request", deny_request_path(user.id), class: "btn btn-default" %><br>
    <% end %>
  <% end %>
<% end %>