config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server, :at => "/resque"

  resources :tools, :posts, :sessions, :users, :events

  resource :calendar, only: [:show], controller: :calendar

  get   "/home/index",            to: "home#index",    as: :home_index
  root                                "home#index",    as: :root

  get   '/auth/twitter/callback', to: 'users#create',  as: :twitter_callback
  post  '/auth/twitter/callback', to: 'users#create'

  get   '/users/:id/confirm',      to: 'users#confirm', as: :confirm_user

  get   '/users/:id/deny_admin',    to: 'users#deny_request', as: :deny_request

  get   '/users/:id/9847hfh9f824oifnsdlkvhosiehlrisklevishfleh', to: 'users#admin_request'
  get   '/users/:id/4ruoirwnv24vpoifho4ehvjrhg4owihfaoihfaajksdhviuwgifbw4f', to: 'users#become_admin', as: :adminify

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GardenRow</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="stylesheets/bootstrap.min.css">
    <link rel="stylesheet" href="stylesheets/style.css">
    <script src="javascripts/jquery-min.js"></script>
    <script src="javascripts/bootstrap.min.js"></script>
    <script src="javascripts/application.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class = "weather">
            <img src="http://openweathermap.org/img/w/<%= @weather.weather_icon %>.png" alt="Weather Icon" >
            <%= @weather.temp.to_i%>º
          </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <!-- <ul class="nav navbar-nav">
            <% if @current_user %>
              <li><%= link_to "Sign Out", session_path(session[:user_id]), method: :delete  %> <span class="sr-only">(current)</span></li>
            <% else %>
              <li><%= link_to 'Sign In With Twitter', 'auth/twitter' %> <span class="sr-only">(current)</span></li>
            <% end %>
          </ul> -->
          <ul class="nav navbar-nav navbar-right">
            <li>
              <!-- <span class="glyphicon glyphicon-home" aria-hidden="true"></span> -->
              <%=link_to "Home", root_path%></li>
            <% if @current_user %>
            <li><%= link_to "My Account", user_path(@current_user.id) %></li>
            <% end %>
            <li>
              <!-- <span class="glyphicons glyphicons-newspaper" aria-hidden="true"></span> -->
              <%=link_to "News", posts_path%>
            </li>
            <li>
              <!-- <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> -->
              <%=link_to "Calendar", calendar_path%>
            </li>
            <li>
              <!-- <span class="glyphicon glyphicon-spade" aria-hidden="true"></span> -->
              <%=link_to "Tools", tools_path%>
            </li>
            <ul class="nav navbar-nav">
              <% if @current_user %>
                <li><%= link_to "Sign Out", session_path(session[:user_id]), method: :delete  %> <span class="sr-only">(current)</span></li>
              <% else %>
                <li><%= link_to 'Sign In With Twitter', 'auth/twitter' %> <span class="sr-only">(current)</span></li>
              <% end %>
            </ul>
            <!-- <li class="active"><a><%= link_to 'Sign In', 'auth/twitter' %> <span class="sr-only">(current)</span></a></li> -->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>